<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.1.0" />
    <None Update="png\pizdak\pizdak-face.png" CopyToOutputDirectory="PreserveNewest" />
    <None Update="png\pizdak\pizdak-hurt.png" CopyToOutputDirectory="PreserveNewest" />
    <None Update="png\pizdak\pizdak-dead.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
